### ISSUE TITLE
Documentation on how to use Polly in this solution

### ISSUE THREAD

**Issue by Jerome2606** [mgj/MvvmCross-Dreams#8]
Hello,

Thanks for your work. I just tested the templates and all is working.

I try to find a good base solution to handle exception.
Actually in get of the property Hello of the first view I add an exception.
This exception doesn't cause crash of the application and that's what I want but it doesn't show to the user that something wrong has happened.

Can you give more informations/documentation on configure polly and Nlog in this template ?

Enhancement:
- preparing to use HockeyApp
- IOS project

**Comment by mgj** [comment]
Hi

I'm very happy that you found the templates useful. I think i understand what you are saying but just to be sure can you please post the code you have issues with? Thanks!

**Comment by Jerome2606** [comment]
I try to find a "Mvvmcross" way to handle globally exception. So I add exception in FirstViewModel:

```
public class FirstViewModel
        : DreamsViewModelBase
    {
        private string _hello = string.Empty;

        public FirstViewModel() : base()
        {
        }

        public string Hello
        {
            get
            {
                return _hello;
            }

            set
            {
                SetProperty(ref _hello, value, "Hello");
                throw new NullReferenceException("Log is null");
                Log.Log("Setting Hello to: " + value);
            }
        }

        private MvxCommand _showSecondCommand;

        public MvxCommand ShowSecondCommand
        {
            get
            {
                _showSecondCommand = _showSecondCommand ?? new MvxCommand(DoShowSecondCommand);
                return _showSecondCommand;
            }
        }

        private void DoShowSecondCommand()
        {
            throw new Exception("Failed to DoShowSecondCommand");
            ShowViewModel<SecondViewModel>(new SecondViewModelBundle() { Data = "Hello from FirstView - " + Hello });
        }
    }
```

I know than in Android I can use UnhandledException and UnhandledExceptionRaiser to catch exception like:

```
protected override void OnCreate(Bundle bundle)
        {
            base.OnCreate(bundle);

            AppDomain.CurrentDomain.UnhandledException += HandleUnhandledException;
            AndroidEnvironment.UnhandledExceptionRaiser += HandleAndroidException;

            Title = DreamsResources.Common_Application_Label;

            SetContentView(ResourceLayoutId);
            PrepareToolbar();

            var thisAsPage = this as TView;
            BindingSet = thisAsPage.CreateBindingSet<TView, TViewModel>();
        }
    protected void HandleUnhandledException(object sender, UnhandledExceptionEventArgs args)
        {
            var e = (Exception)args.ExceptionObject;
            Mvx.Trace(MvxTraceLevel.Error, "Exception: {0}", e.ToLongString());
            var logReader = new LogService();
            var logMessages = logReader.ReadLog("mvx:E");
            var customData = new Dictionary<string, string> { { "logMessage", logMessages } };
            
        }

        protected void HandleAndroidException(object sender, RaiseThrowableEventArgs e)
        {
            var exception = e.Exception;
            Mvx.Trace(MvxTraceLevel.Error, "Exception: {0}", e.Exception.ToLongString());
            var logReader = new LogService();
            var logMessages = logReader.ReadLog("mvx:E");
            var customData = new Dictionary<string, string> { { "logMessage", logMessages } };
            //var session = SessionController.Instance;
            //var user = new RaygunIdentifierMessage(session.UserName + " " + session.Company);
            //var rayMessage = RaygunMessageBuilder.New
            //    .SetEnvironmentDetails()
            //    .SetMachineName(Environment.MachineName)
            //    .SetClientDetails()
            //    .SetExceptionDetails(exception)
            //    .SetUser(user)
            //    .SetUserCustomData(customData)
            //    .Build();
            //RaygunClient.Current.Send(rayMessage);

            
        }
```

Here my problems is that I can't manage to handle exception from the core PCL. And I would like that the application doesn't crash but display a dialog message like "An error has occured".

My question about NLog are where can I configure NLog to see these two exception with the stacktrace
Did we have all the power of NLog config like send Email for level upper to Error ? How can I access log file maybe to send it by webservice ?

**Comment by mgj** [comment]
Thank you

This may sound strange to you, but i highly recommend that you actually let your app crash instead of showing a dialog. This is because you are unlikely to be able to recover in any worthwhile manner (the exception got through all your catch-blocks which contains all your error handling). Once you find out a crash happened, you can add error handling where the exception was thrown instead of in some outer catch-all scope.

I have not yet tried to use the built-in email feature of NLog, but I would very much like to know if you manage to get it working (and as always pull requests are very much appreciated :))

Throwing an exception in the Hello property *should* cause the app to crash. I will look into it further and get back to you.

**Comment by Jerome2606** [comment]
I don't want to handle exception with a try catch everywhere. I develop a lot of Web application and the first thing I do is to override OnException method to load my error block.

Let's the application simply crash is not a solution. Because when you open back the application if you get an exception in some specific view, the application will return to the last state and will crash again.

Before interesting in Xamarin I was used to develop in Cordova and was using http://justin-credible.github.io/Ionic-TypeScript-Starter/ 
This was very nice to intercept all error and let us decide what we prefer to do in each case.

About NLog, do you have an idea on where I should put the "NLog.config" ?

**Comment by mgj** [comment]
> I don't want to handle exception with a try catch everywhere.

You *should* want that. Its much better than having all error handling in one place - doing so is an anti-pattern. You should be handling the error where it (can) happen, as soon as possible. AppDomain.CurrentDomain.UnhandledException should *only* be used if you are writing your own crashlogger, and even then you *still* want to handle exceptions with try-catch everywhere.

> Let's the application simply crash is not a solution. Because when you open back the application if you get an exception in some specific view, the application will return to the last state and will crash again.

You think showing the same error dialog over and over, not letting the user use the app, is any better?

In the templates we configure NLog in code, instead of using the config file. I believe you can set any configuration in code, that you can in the configuration file. Please correct me if this is not true

**Comment by Jerome2606** [comment]
Ok thank you for your response.

I will check about the possibilities of configuration.

Again thank you for your template, I believe that it can answer to lot of users research.

**Comment by mgj** [comment]
Its me who should say thanks. These questions and discussions are essential to improving the templates.

I hope you dont mind me reopening the issue so that I can look into the "Hello-exception" thing

**Comment by mgj** [comment]
I finally got around to testing this, and with the newest version of xamarin + mvvmcross you *DO* get an exception:

`[0:] MvxBind:Error:  6.67 SetValue failed with exception - TargetInvocationException: Exception has been thrown by the target of an invocation.
	  at System.Reflection.MonoMethod.Invoke (System.Object obj, System.Reflection.BindingFlags invokeAttr, System.Reflection.Binder binder, System.Object[] parameters, System.Globalization.CultureInfo culture) [0x00050] in /Users/builder/data/lanes/3511/501e63ce/source/mono/mcs/class/corlib/System.Reflection/MonoMethod.cs:313 
  at System.Reflection.MonoProperty.SetValue (System.Object obj, System.Object value, System.Reflection.BindingFlags invokeAttr, System.Reflection.Binder binder, System.Object[] index, System.Globalization.CultureInfo culture) [0x0006a] in /Users/builder/data/lanes/3511/501e63ce/source/mono/mcs/class/corlib/System.Reflection/MonoProperty.cs:445 
  at System.Reflection.PropertyInfo.SetValue (System.Object obj, System.Object value, System.Object[] index) [0x00000] in /Users/builder/data/lanes/3511/501e63ce/source/mono/mcs/class/corlib/System.Reflection/PropertyInfo.cs:111 
  at MvvmCross.Binding.Bindings.Source.Leaf.MvxLeafPropertyInfoSourceBinding.SetValue (System.Object value) [0x00060] in D:\git\MvvmCross\MvvmCross\Core\Binding\Bindings\Source\Leaf\MvxLeafPropertyInfoSourceBinding.cs:83 
InnerException was NullReferenceException: Log is null`

I'm closing this issue
